### PR TITLE
Wip 12 create store table schema

### PR DESCRIPTION
**Pull request by realJohnAdex**
Create the store table schema and request a pull to main if satisfactory.

### CODE REVIEW

**Review by samdoghor — APPROVED** [review]

**Comment by samdoghor** [comment]
Update address datatype to text and make a pull request again

**Comment by realJohnAdex** [comment]
Should the branch be restored or i can just create a new branch

**Comment by samdoghor** [comment]
You can create a new branch

**Comment by realJohnAdex** [comment]
Okay, thanks I'm on it now. Should I retain the NOT NULL constraint?

**Comment by realJohnAdex** [comment]
i have retained the constraint and made the PR

**Pull request merged**
