### PR TITLE
Schema for order details

### PR DESCRIPTION
**Pull request by Abednego-py**

### CODE REVIEW

**Review by samdoghor — CHANGES_REQUESTED** [review]
- Thank you. Put you SKU in lowercase
- Status datatype should be VARCHAR
- You didn't indicate your foreign keys or action to take upon update or delete of foreign keys.

See https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-foreign-key/

**Comment by Abednego-py** [comment]
Alright. The status field can take only two values(true of false). I don't see why it should not be a Boolean data type.

**Comment by Abednego-py** [comment]
I have made the changes you requested and created an enum for the status field.

**Review by samdoghor — APPROVED** [review]
Thank you

**Pull request merged**
