### PR TITLE
Wrote schema for reviews table in gomerce psql file

### PR DESCRIPTION
**Pull request by iamlawrenceonoja**

### CODE REVIEW

**Review by samdoghor — CHANGES_REQUESTED** [review]
Well done! ☺️.

Please remove quotation marks on your comment row.

Also, there is no action taken when foreign key(s) is delete from current table. Actions such as cascade, or set null etc.

**Comment by iamlawrenceonoja** [comment]
I have made the requested changes.

**Review by samdoghor — CHANGES_REQUESTED** [review]
Perfect, but the file you PR for is outdated. Use `git pull` to get the latest version of the file before editing and making your PR.

Reference the document below to properly format the foreign key. 
https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-foreign-key/

Lastly our table names are singular.

Thank you.

**Review by samdoghor — CHANGES_REQUESTED** [review]
The correction are right but one thing is remaining. Sorry we are going back and forth on this. Please pull the latest version of the file from the repo. Thank you.

**Review by samdoghor — CHANGES_REQUESTED** [review]
I will reach out to you.

**Pull request closed without merging**
